// Define TypeScript interfaces for data structure
export interface Subtopic {
  name: string;
  questions: number;
  source?: string;
  subtopics?: Subtopic[] | string[]; // optional nested subtopics or string array for simpler subtopics
}

export interface Chapter {
  name: string;
  questions: number;
  source: string;
  subtopics?: Subtopic[];
}

// English chapters data
export const englishChapters: Chapter[] = [
  { name: "Spot the Error", questions: 716, source: "api" },
  { name: "Sentence Improvement", questions: 790, source: "json" },
  { name: "Narration", questions: 245, source: "api" },
  { name: "Active Passive", questions: 250, source: "api" },
  { name: "Para Jumble", questions: 207, source: "api" },
  { name: "Fill in the Blanks", questions: 665, source: "api" },
  { name: "Cloze Test", questions: 860, source: "api" },
  { name: "Comprehension", questions: 248, source: "api" },
  { name: "One Word Substitution", questions: 681, source: "api" },
  { name: "Idioms", questions: 762, source: "api" },
  { name: "Synonyms", questions: 765, source: "api" },
  { name: "Antonyms", questions: 740, source: "api" },
  { name: "Spelling Check", questions: 632, source: "api" },
  { name: "Homonyms", questions: 42, source: "api" },
];

// GK chapters data with nested subtopics
export const gkChapters: Chapter[] = [
  {
    name: "Static G.K.",
    questions: 2095,
    source: "pdf",
    subtopics: [
      { name: "Dance", questions: 142 },
      { name: "Arts Personality", questions: 291 },
      { name: "Arts Awards", questions: 24 },
      { name: "Musical Instruments", questions: 65 },
      { name: "Festivals", questions: 170 },
      { name: "Fairs", questions: 20 },
      { name: "Songs", questions: 60 },
      { name: "Painting/Dress/Tribes", questions: 31 },
      { name: "First In India/Word", questions: 67 },
      { name: "Sports", questions: 309 },
      { name: "Books And Authors", questions: 201 },
      { name: "Famous Personality", questions: 29 },
      { name: "Important Days", questions: 46 },
      { name: "States GK", questions: 113 },
      { name: "Organisation", questions: 68 },
      { name: "World GK", questions: 34 },
      { name: "Computer", questions: 104 },
      { name: "Full Forms", questions: 13 },
      { name: "Religious Places", questions: 49 },
      { name: "Awards", questions: 46 },
      { name: "Important events", questions: 35 },
      { name: "Founders", questions: 9 },
      { name: "Schemes", questions: 86 },
      { name: "Miscellaneous", questions: 86 },
    ],
  },
  {
    name: "History",
    questions: 924,
    source: "pdf",
    subtopics: [
      {
        name: "Ancient",
        questions: 300,
        subtopics: [
          "Prehistoric Cultures in India",
          "Vedic-age",
          "Jainism",
          "Buddhism",
          "Mahajanapadas",
          "Mauryan-dynasty",
          "Gupta-dynasty",
          "Vardhana-dynasty",
          "Chola-dynasty",
          "Miscellaneous",
        ],
      },
      {
        name: "Medieval",
        questions: 300,
        subtopics: [
          "Foreign invasions",
          "Delhi sultanate",
          "Slave dynasty",
          "Khilji dynasty",
          "Tughlaq dynasty",
          "Sayyid dynasty",
          "Lodi dynasty",
          "Mughal period",
          "Babur",
          "Humayun and sher shah suri",
          "Akbar",
          "Jahangir",
          "Shah jahan",
          "Aurangzeb",
          "Sikh-guru",
          "Maratha empire",
          "Vijayanagar empire",
          "Wars and treaties",
          "Medieval Miscellaneous",
        ],
      },
      {
        name: "Modern",
        questions: 324,
        subtopics: [
          "Revolt of 1857",
          "Governors and Viceroys",
          "British acts and policies",
          "Partition and swadeshi movements",
          "Gandhian Era",
          "Expansion of british rule",
          "Revolutionaries",
          "Struggle for independence",
          "Socio religious reforms",
          "Indian National Congress Sessions",
          "Muslim-league",
          "Modern Miscellaneous",
        ],
      },
    ],
  },
  {
    name: "Polity",
    questions: 500,
    source: "pdf",
    subtopics: [
      {
        name: "Indian Constitution",
        questions: 255,
        source: "pdf",
        subtopics: [
          { name: "Constitution", questions: 34 },
          { name: "Sources of Indian Constitution", questions: 13 },
          { name: "Article, Schedule, Parts and list", questions: 114 },
          { name: "Amendments", questions: 39 },
          { name: "Fundamental Rights and Duties", questions: 55 },
        ],
      },
      {
        name: "Indian Governance",
        questions: 245,
        source: "pdf",
        subtopics: [
          { name: "Committee Reports", questions: 13 },
          { name: "Parliament", questions: 45 },
          {
            name: "President, Vice President and Prime Minister",
            questions: 50,
          },
          { name: "Judiciary", questions: 28 },
          { name: "Government Bodies", questions: 30 },
          { name: "Polity of neighbouring countries", questions: 5 },
          { name: "Polity Miscellaneous", questions: 74 },
        ],
      },
    ],
  },
  {
    name: "Geography",
    questions: 909,
    source: "pdf",
    subtopics: [
      { name: "Solar system and its planets", questions: 44 },
      { name: "Longitudes and latitudes", questions: 16 },
      { name: "Continents and Oceans", questions: 42 },
      { name: "Neighbouring Countries of India", questions: 12 },
      { name: "Indian Drainage System", questions: 123 },
      { name: "World Drainage System", questions: 13 },
      { name: "Minerals and Energy Resources in India", questions: 48 },
      { name: "Agriculture", questions: 74 },
      { name: "Soil", questions: 33 },
      { name: "Vegetation", questions: 40 },
      { name: "Climate", questions: 59 },
      { name: "Industries", questions: 32 },
      { name: "Biosphere Reserves", questions: 34 },
      { name: "Physiographic Division of India", questions: 45 },
      { name: "Transportation", questions: 45 },
      { name: "Population", questions: 94 },
      { name: "Atmosphere", questions: 18 },
      { name: "Rocks", questions: 16 },
      { name: "Mountain", questions: 38 },
      { name: "Volcano", questions: 3 },
      { name: "World geography and Map", questions: 19 },
      { name: "Geography Miscellaneous", questions: 61 },
    ],
  },
  {
    name: "Economics",
    questions: 444,
    source: "pdf",
    subtopics: [
      { name: "Basics of Economy", questions: 33 },
      { name: "Concepts of Demand and Supply", questions: 11 },
      { name: "Cost, Production, Consumption and Market", questions: 16 },
      {
        name: "National Income, Inflation, Budget, Taxation and GDP",
        questions: 94,
      },
      { name: "Money Banking and Financial Institutions", questions: 108 },
      { name: "Navratna / Maharatna / PSUs", questions: 8 },
      { name: "International Organisations", questions: 4 },
      { name: "Government Schemes", questions: 38 },
      { name: "Five - Year Plans", questions: 23 },
      { name: "Indian Economy : Central Problems and Planning", questions: 40 },
      { name: "Stock, Debentures and Foreign trade", questions: 11 },
      { name: "Fiscal Policy and Monetary Policy", questions: 22 },
      { name: "Economics Miscellaneous", questions: 36 },
    ],
  },
  {
    name: "Physics",
    questions: 251,
    source: "pdf",
    subtopics: [
      { name: "Light and Optics", questions: 22 },
      { name: "Heat and Thermodynamics", questions: 14 },
      { name: "Fluid Mechanics", questions: 5 },
      { name: "Electric Current and Its Effects", questions: 40 },
      { name: "Force and Pressure", questions: 34 },
      { name: "Sound", questions: 9 },
      { name: "Gravitation", questions: 6 },
      { name: "Work and Energy", questions: 11 },
      { name: "Wave", questions: 13 },
      { name: "Radioactivity", questions: 6 },
      { name: "Discoveries", questions: 36 },
      { name: "Units and Measurements", questions: 34 },
      { name: "Physics Miscellaneous", questions: 21 },
    ],
  },
  {
    name: "chemistrychapters",
    questions: 486,
    source: "pdf",
    subtopics: [
      { name: "Structure of Atom", questions: 24 },
      { name: "Metals, Non-metals and Alloys", questions: 29 },
      { name: "Acid, Bases and Salt", questions: 30 },
      { name: "Metallurgy", questions: 10 },
      { name: "Organic Chemistry", questions: 65 },
      { name: "Periodic Table", questions: 63 },
      { name: "Ideal Gas Law", questions: 9 },
      { name: "Chemical Properties", questions: 49 },
      { name: "Solutions", questions: 12 },
      { name: "Chemistry in Everyday Life", questions: 65 },
      { name: "Discoveries", questions: 44 },
      { name: "Common Name", questions: 38 },
      { name: "Chemistry Miscellaneous", questions: 48 },
    ],
  },
  {
    name: "Biology",
    questions: 552,
    source: "pdf",
    subtopics: [
      { name: "Scientific Name", questions: 8 },
      { name: "Nutrition in Animals", questions: 29 },
      { name: "Nutrition in Plants", questions: 26 },
      { name: "Deficiency and Diseases", questions: 67 },
      { name: "Reproduction in Animals", questions: 9 },
      { name: "Reproduction in Plants", questions: 10 },
      { name: "Cell: Basic Unit of life", questions: 102 },
      { name: "Sensory Organs", questions: 7 },
      { name: "Circulatory System", questions: 11 },
      { name: "Excretory System", questions: 4 },
      { name: "Endocrine/Exocrine System", questions: 7 },
      { name: "Respiratory System", questions: 8 },
      { name: "Digestive System", questions: 17 },
      { name: "Nervous System", questions: 7 },
      { name: "Skeleton System", questions: 8 },
      { name: "Plant Kingdom", questions: 54 },
      { name: "Animal Kingdom", questions: 62 },
      { name: "Micro Organism", questions: 21 },
      { name: "Enzymes and Hormones", questions: 16 },
      { name: "Discoveries and Vaccines", questions: 26 },
      { name: "Scientific Study", questions: 9 },
      { name: "Biology Miscellaneous", questions: 48 },
    ],
  },
  {
    name: "Current Affairs",
    questions: 500,
    source: "pdf",
    subtopics: [
      { name: "Sports", questions: 108 },
      { name: "Special Days", questions: 4 },
      { name: "Awards", questions: 41 },
      { name: "Persons", questions: 90 },
      { name: "States", questions: 38 },
      { name: "Schemes and Projects", questions: 96 },
      { name: "Economics", questions: 24 },
      { name: "Polity", questions: 57 },
      { name: "Current Affairs Miscellaneous", questions: 42 },
    ],
  },
];
